on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish_docker:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
      
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 'lts/*'
      
      - name: Install npm dependencies
        run: npm ci
        working-directory: Meziantou.OnlineVideoPlayer
      
      - name: Compile TypeScript
        run: npm run build
        working-directory: Meziantou.OnlineVideoPlayer
      
      - name: Log in to Docker
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create image
        run: dotnet publish Meziantou.OnlineVideoPlayer/Meziantou.OnlineVideoPlayer.csproj --os linux --arch x64 --configuration Release /t:PublishContainer /bl:publish.binlog

      - name: Upload binlog
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: binlog
          path: "**/*.binlog"
